name: movie_app
description: "Movie Explorer - GetX + Firebase Auth"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.7.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0

  # Networking
  http: ^1.5.0

  # Caching
  cached_network_image: ^3.4.1

  # Storage
  shared_preferences: ^2.5.3

  # Routing
  go_router: ^16.0.0

  # UI
  cupertino_icons: ^1.0.8

  # Secure storage for secrets
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0F1923"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter:
  uses-material-design: true

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf