// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvPjTt5ZmWJL_G-v4vcGJ5xvopIDau-OA',
    appId: '1:834438858975:web:619b20714b8480fab9416a',
    messagingSenderId: '834438858975',
    projectId: 'fir-auth-4c440',
    authDomain: 'fir-auth-4c440.firebaseapp.com',
    storageBucket: 'fir-auth-4c440.firebasestorage.app',
    measurementId: 'G-H647QCXS8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQbmApxPw4aDVNtTFdLmzz6xqQG4XqO4E',
    appId: '1:834438858975:android:d778947aca4cd030b9416a',
    messagingSenderId: '834438858975',
    projectId: 'fir-auth-4c440',
    storageBucket: 'fir-auth-4c440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ykfsI6ZTvR_wsm7K6p7TMKwKfRBViXk',
    appId: '1:834438858975:ios:a65fa482d4fb7f00b9416a',
    messagingSenderId: '834438858975',
    projectId: 'fir-auth-4c440',
    storageBucket: 'fir-auth-4c440.firebasestorage.app',
    iosClientId:
        '834438858975-oj1sfosi9atmg8ek2icim3a9gm40he68.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ykfsI6ZTvR_wsm7K6p7TMKwKfRBViXk',
    appId: '1:834438858975:ios:a65fa482d4fb7f00b9416a',
    messagingSenderId: '834438858975',
    projectId: 'fir-auth-4c440',
    storageBucket: 'fir-auth-4c440.firebasestorage.app',
    iosClientId:
        '834438858975-oj1sfosi9atmg8ek2icim3a9gm40he68.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvPjTt5ZmWJL_G-v4vcGJ5xvopIDau-OA',
    appId: '1:834438858975:web:8332e27205a9474cb9416a',
    messagingSenderId: '834438858975',
    projectId: 'fir-auth-4c440',
    authDomain: 'fir-auth-4c440.firebaseapp.com',
    storageBucket: 'fir-auth-4c440.firebasestorage.app',
    measurementId: 'G-2KW3316F3T',
  );
}
